version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: es-ml
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false        # no auth for local lab
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana-ml
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"

  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.9
    container_name: logstash-ml
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    environment:
      - LS_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      # pipeline config
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      # sample data for the file input
      - ./logstash/data:/usr/share/logstash/data

volumes:
  esdata:
